server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Gateway Route
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=parking-space-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://PARKING-SPACE-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/parking/**

spring.cloud.gateway.server.webmvc.routes[2].id=vehicle-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://VEHICLE-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/vehicles/**

spring.cloud.gateway.server.webmvc.routes[3].id=payment-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/payments/**

